5578131
krsy0411/12thFEStudy pull request #18
Opened 2024-04-09 16:29 UTC by YeongJunJeong

2024-04-09 16:29 UTC, YeongJunJeong commented
5578131

2024-04-11 06:32 UTC, krsy0411 requested changes

2024-04-11 06:32 UTC, krsy0411 commented on 3rd/과제_css.css
> +  font-weight: 400;
아마 googlefonts에서 oswald 사용법 보시면, css에서 weight는 200이나 700을 권장한다고 해놨을거예요. 지금이야 괜찮지만, 끌어다 쓰는 경우엔 웬만하면 제공되는 형식에 맞춰서 사용하시는 습관을 들으시면 좋을듯!

2024-04-11 06:46 UTC, YeongJunJeong commented on 3rd/과제_css.css
> +  font-weight: 400;
넵 감사합니다!!!

2024-04-11 06:53 UTC, merged