이상현
krsy0411/12thFEStudy pull request #40
Opened 2024-06-29 06:48 UTC by idealHyun

2024-06-29 06:49 UTC, idealHyun commented
![알림](https://github.com/krsy0411/12thFEStudy/assets/118160647/3c0550c2-0617-4b5f-a9b6-56523550de1e)

2024-06-30 06:42 UTC, krsy0411 commented on Notification/5584929/index.html
> +            <i class="fa-solid fa-xmark notification__close__button"
여기에 notification__close_button이라는 클래스명을 추가

2024-06-30 06:42 UTC, krsy0411 commented on Notification/5584929/script.js
> +const notificationCloseButton=document.querySelector(".notification__close__button");
새로운 변수 생성

2024-06-30 08:26 UTC, krsy0411 requested changes

2024-06-30 08:26 UTC, krsy0411 commented on Notification/5584929/script.js
classname을 추가해서 해당 querySelector변수를 만들어서 eventListener를 추가하신 것도 좋은 방법인 것 같습니다.
이 시점부턴 정말 팀이 약속한 작성방식에 따라 옳고 그름을 따질 수 있을 것 같네요. 물론 저는 규칙을 따로 설정한 것은 아니기에 맞다고 얘기하지만, 정말 이게 최선이었나라는 의문점을 상현님이 갖고 판단해보시면 좋을 것 같습니다.

우선, classname을 추가하고 해당 클래스네임을 찾는 selector를 통해 변수를 만든건 필연적으로 필요한 내용 같네요(맞겠죠?)
그렇다면 제가 제3자의 동료 개발자의 시점으로서, 왜 showToastMessageButton, notificationCloseButton에 직접적으로 eventListener를 생성하는 코드를 따로 분리시켰는지 물어볼 것 같습니다(과연 이렇게 따로 분리시키는게 좋았을까요? 아니면 document eventListener에 해당 로직을 조건문으로 합쳐서 관리하는 편이 좋았을까요? 그리고 이런 행위는 더 나아가 확장성이 더 좋은 형태인가요? 아니면 안 좋은 형태인가요?)
이에 대해 명확한 대답을 저도 내놓지는 못 할 것 같습니다. 그런 것까지 고려해 알려주고자 한 스터디도 아니구요. 하지만 한 번 더 생각해보시면 좋은 생각들이 상현님한테 떠오를 것 같습니다:D

2024-06-30 08:30 UTC, krsy0411 commented
@idealHyun
comment 읽어봐주시고 이모지 달아두고 댓글에 멘션해주시면 머지할게요:)

2024-06-30 10:18 UTC, idealHyun commented
@krsy0411 
먼저, 코드를 작성할 때 기능 구현에 대해서만 생각하고 깊이 있게 고민을 안했던 것 같습니다.
그리고 document에 eventListener를 다는 것이 왜인지 모를 어색함이 느껴졌던 것 같습니다.(너무 상위에 있는 요소라 생각이 되었던 것 같습니다.)
확장성이나 유지보수를 생각하면 이벤트 위임을 이용하여 상위요소에 묶는 것이 더 좋다고 생각이되었습니다.
좋은 코멘트 남겨주셔서 감사합니다 👍

2024-06-30 10:23 UTC, krsy0411 commented
> @krsy0411 먼저, 코드를 작성할 때 기능 구현에 대해서만 생각하고 깊이 있게 고민을 안했던 것 같습니다. 그리고 document에 eventListener를 다는 것이 왜인지 모를 어색함이 느껴졌던 것 같습니다.(너무 상위에 있는 요소라 생각이 되었던 것 같습니다.) 확장성이나 유지보수를 생각하면 이벤트 위임을 이용하여 상위요소에 묶는 것이 더 좋다고 생각이되었습니다. 좋은 코멘트 남겨주셔서 감사합니다 👍

무조건 최상위 요소에 `event`인자를 활용해 `event.target`이 일치하는지 체크하는 방식으로 위임하는게 정답은 아닙니다.
각 이벤트 리스너가 내부에서 하는 행위가 많다면

2024-06-30 10:25 UTC, krsy0411 approved these changes

2024-06-30 10:26 UTC, merged