신호철
krsy0411/12thFEStudy pull request #41
Opened 2024-06-30 08:02 UTC by slo0ey

![화면 기록 2024-06-30 오후 4 57 18](https://github.com/krsy0411/12thFEStudy/assets/49348248/40e1a28e-2905-4e3f-9f47-8e63bce38a87)

2024-06-30 08:32 UTC, krsy0411 requested changes
@slo0ey
호철님 AnimatedText까지 얹어서 PR 올리신 거 같은데 확인 한 번 부탁드려요

2024-06-30 08:37 UTC, krsy0411 commented
> @slo0ey 호철님 AnimatedText까지 얹어서 PR 올리신 거 같은데 확인 한 번 부탁드려요

작업물은 다 하시고 커밋 다 찍어놓고 Pull 깜빡하셔서 커밋 덮어씌우다가 생긴 거 같긴 하네요. 머지할때 문제가 생길 거 같지는 않아요. 근데 커밋메세지가 좀 엉키는거 같아서, 서칭해보시고 커밋 변경해서 강제로 push해보시겠어요?

2024-07-01 07:01 UTC, slo0ey commented
커밋 변경해서 다시 푸시했습니다!

2024-07-01 08:07 UTC, krsy0411 commented on Notification/5701866/index.html
> +          class="notification-close"
`notification-close` 클래스 네임을 추가해서 js에서 DOM API를 잘 사용하셨네요:)

2024-07-01 08:07 UTC, krsy0411 commented on Notification/5701866/script.js
> +    isCloseButtonClicked
맞아요. 제 의도는 이거긴 해요.
변수 하나만 생성 -> 조건문에 OR 논리연산자 사용 -> 어느 한쪽의 경우에 만족하면 클래스네임`add`을 추가하는 것

그렇다면 여기서 좀 더 개선해볼만한 점도 있을까 한 번 생각해볼까요?
(아마 이 시점부턴 팀의 코드 작성 규칙에 따라 달라지겠죠? 즉 틀렸다는 의견이 아닙니다. 그냥 이런 방식도 있다의 `생각 확장시키기`라고 보면 좋을 거 같네요)
```javascript
const notification = document.querySelector(".notification");
const button = document.querySelector(".trigger-button");
const closeButton = document.querySelector(".notification-close");

document.addEventListener('click', (e) => {
    const target = e.target;

    // Show Toast Message 버튼 클릭 시 notification 보이기
    if (target === button) {
        notification.classList.remove('hidden');
        notification.classList.add('none');
    }
    // notification 내 x 버튼 클릭 시 notification 숨기기
    else if (target === closeButton) {
        notification.classList.add('hidden');
        notification.classList.add('none');
    }
    // notification과 Show Toast Message 버튼 외의 영역 클릭 시 notification 숨기기
    else if (!notification.contains(target)) {
        notification.classList.add('hidden');
        notification.classList.add('none');
    }
});
```
이렇게 하면, toggleNotification 함수를 제거해도 문제가 안 될 듯 합니다(아마도?). 그러면 좀 더 html파일과 js파일을 분리시켰으니 추후에 코드가 수정되어도 index.html 파일을 살펴볼 필요가 없을 듯 하네요.

이 시점에서는 비슷해보이는 부분들이 좀 있어보이네요(아 추상화 마렵다. 그쵸?).
근데 여기서는 고민해볼 필요가 있습니다. 괜히 추상화를 시켜서 함수 블록을 만들었는데, 추후에 예상치 못한 `classname`이 더 생긴다면? 오히려 `classname`을 늘려놨는데 사라진다면? 이 부분은 앞으로의 확장성에 대해 좀 더 고려해보고 해도 늦지 않을 것 같습니다. 적어도 저는 그랬던 것 같아요. 해커톤때도 너무 함수로만 다 분리하려고 하지 말고, 좀 더 기다려봤다가 확실할거 같을때에 추상화 작업을 수행해도 좋을 거 같아요.

수고하셨고, 읽어보시고 이 댓글에 이모지 달아주시면 머지하도록 할게요~

2024-07-01 08:13 UTC, krsy0411 approved these changes

2024-07-01 08:46 UTC, merged