내이름은 김현민
krsy0411/12thFEStudy pull request #42
Opened 2024-06-30 08:30 UTC by baekggum

ㅎㅇㅎㅇ

2024-06-30 08:38 UTC, krsy0411 commented
@baekggum 
움짤 같이 올려달라고 했을텐데...🙂

2024-06-30 08:49 UTC, baekggum commented
https://github.com/krsy0411/12thFEStudy/assets/49273517/460a28b9-237f-45b5-bd38-4aa1b5595f5c

감사합니다

2024-06-30 09:06 UTC, krsy0411 commented on Notification/5585358/index.html
svg에 onclick 이벤트 건거 확인

2024-06-30 09:23 UTC, krsy0411 commented on Notification/5585358/index.html
> +    <button class="trigger-button" onclick="toggleNotification()">
이거 잘못 작성한 거 아님? 소괄호 끼고 바로 실행하면 안되지 않나?

2024-06-30 09:23 UTC, krsy0411 commented on Notification/5585358/index.html
> +    <button class="trigger-button" onclick="toggleNotification()">
그리고 이 버튼에 toggleNotification이 들어가있으면 안되지 않음??
hide랑 none이 오히려 생기는 add method가 들어가줘야하는 부분 같은데 확인해줘

2024-07-01 08:10 UTC, krsy0411 commented on Notification/5585358/index.html
> +    <button class="trigger-button" onclick="toggleNotification()">
아아 맞는 코드네 제가 착각햇다 ㅇㅋ

2024-07-01 08:14 UTC, krsy0411 requested changes

2024-07-01 08:14 UTC, krsy0411 commented on Notification/5585358/script.js
근데 이거 X 누르면 사라지는 건 맞는데, 검은 바탕화면 눌러도 사라지는 로직이 날아갔음(codespace로 확인함)
수정해서 다시 PR 부탁드려요

2024-07-01 11:26 UTC, baekggum commented on Notification/5585358/script.js
사실 검은 바탕 눌렀을 때 사라지게하는건 일부로 x만 눌렀을 때 삭제 할 수 있게끔 만든거라 괜찮지 않을까요? 선생님??

2024-07-01 14:48 UTC, krsy0411 commented on Notification/5585358/script.js
? 고치세요😊

2024-07-07 09:01 UTC, krsy0411 approved these changes

2024-07-07 09:01 UTC, merged